# Use the official PHP image as the base image for CLI
FROM php:8.2-fpm AS php-cli

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    unzip \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure zip \
    && docker-php-ext-install zip pdo pdo_mysql

# Install Redis extension
RUN pecl install redis && docker-php-ext-enable redis

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Node.js and npm
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs \
    && curl -L https://www.npmjs.com/install.sh | sh

# Avoid warnings by setting the frontend to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Load ini config for change values
COPY ./php.ini /usr/local/etc/php/conf.d/custom-php.ini

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Set the working directory in the container
WORKDIR /var/www/html

# Start PHP-FPM
CMD ["php-fpm"]
